version: '3.8'

services:

  back_end_server:
    env_file:
      - .env
      - .env_dev.env
    volumes:
      - type: bind
        source: ./data/users_photos_dev
        target: /usr/assets/users_photos
    command: npm run start:dev
