version: '3.8'

volumes:
  node_modules_guest_back:
  node_modules_guest_front:

services:

  database_server:
    image: postgres
    env_file:
      - .env
      - .env_prod.env
      - .env_prod_database.env
    ports:
      - 5432:5432
    volumes:
      - ./database/:/var/lib/postgresql/data/

  back_end_server:
    build: ./back_end
    restart: always
    env_file:
      - .env
      - .env_prod.env
      - .env_prod_database.env
    volumes:
      ### Important to make sure node_module is not imported from local
      - node_modules_guest_back:/usr/src/app/node_modules
      - ./back_end:/usr/src/app
      - type: bind
        source: ./data/users_photos_prod
        target: ${USERS_PHOTOS_STORAGE_PATH}
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:prod

  front_end_server:
    build: ./front_end
    restart: always
    volumes:
      ### Important to make sure node_module is not imported from local
      - node_modules_guest_front:/usr/src/app/node_modules
      - ./front_end:/usr/src/app
    ports:
      - 3001:3000
    command: npm run start
