version: '3.8'

services:

  database_server:
    command: 'echo "No database server in dev environnement"'

  back_end_server:
    env_file:
      - .env
      - .env_prod.env
      - .env_dev.env
    volumes:
      - type: bind
        source: ./data/users_photos_dev
        target: ${USERS_PHOTOS_STORAGE_PATH}
    command: npm run start:dev
